blog/config/routes.rb
Rails.application.routes.draw do
resources :posts do
resources :comments
end
root to: "posts#index"
resources :sessions, only: [:new, :create, :destroy]
  match 'signin',   to: 'sessions#new',     via: 'get'
  match 'signout',  to: 'sessions#destroy', via: 'delete'
end

blog/app/models/admin.rb
class Admin < ActiveRecord::Base

before_save { self.email = email.downcase }
validates :name, presence: true, length: { maximum: 50 }

 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

has_secure_password
  validates :password, length: { minimum: 6 }

end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

blog/app/models/post.rb
class Post < ActiveRecord::Base
has_many :comments
validates :title, presence: true, length: {maximum: 60}
	validates :body, presence: true
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  include SessionsHelper
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
    	@comment = @post.comments.create(params[:comment].permit(:author, :body))

	    redirect_to post_path(@post)
	end
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to @post
  end

  def show
    @post = Post.find(params[:id])
  end

	def index
		@posts = Post.all.order('created_at DESC').paginate(page: params[:page], per_page: 2)
	end


  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
	admin = Admin.find_by(email: params[:session][:email].downcase)
		if admin && admin.authenticate(params[:session][:password])
			sign_in admin
			redirect_to root_url
		else
			if admin
				message = "Password salah"
			else
				message = "Email tidak terdaftar"
			end
			flash.now[:error] = message
			render 'new'
		end

	end

		def destroy
		sign_out
		redirect_to root_url
	end

end

end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(admin)
		remember_token = Admin.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		admin.update_attribute(:remember_token, Admin.encrypt(remember_token))
		self.current_admin = admin
	end

	def current_admin=(admin)
		@current_admin = admin
	end

	def current_admin
		remember_token = Admin.encrypt(cookies[:remember_token])
		@current_admin ||= Admin.find_by(remember_token: remember_token)
	end

	def admin?
		!current_admin.nil?
	end

	def sign_out
		self.current_admin = nil
		cookies.delete(:remember_token)
	end


end

blog/app/views/layouts/application.html.erb
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="id">
<html>
<head>
  <title>Blogku</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
	<body>
<nav class="navbar navbar-fixed-top" role="navigation">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "Blog", root_url, class: "brand" %>
				<ul class="nav pull-right">
					<% if !admin? %>
						<li><%= link_to "Admin", signin_url %></li>
					<% else %>
						<li><%= link_to "Logout", signout_url, method: "delete" %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>
	<div class="container">
		<div id="content">
<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
			<%= yield %>
		</div>
	</div>

</body>
</html>

blog/app/views/posts/index.html.erb
<h4>Daftar tulisan</h4>

<%= link_to "Tulis artikel", new_post_url %>

<%= will_paginate %>

<ul class="posts">
	<% @posts.each do |post| %>
		<h5><div class="title"><%= link_to post.title, post%></div>
		<em><small><%= l post.created_at, format: :short %></small></em></h5>
		<div class="body"><%= post.body %></div>
		<div class="comments"><small><%= link_to "#{post.comments.count} komentar", post %></small></div>
		<hr>
	<% end %>
</ul>

<%= will_paginate %>

blog/app/views/posts/new.html.erb
<%= form_for :post, url: posts_path do |f| %>
  <p>
    <%= f.label :judul %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :isi %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

blog/app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<p>
     <%= @post.body %>
</p>

<!-- komentar -->

<h4>Komentar</h4>
<% @post.comments.each do |comment| %>
  <p>
    <strong><%= comment.author %>
    </strong>
    <small><%= l comment.created_at, format: :long %></small> <br />
    <%= comment.body %>
  </p>
<% end %>
<hr>


<h4>Tambahkan komentar:</h4>
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :Nama %><br />
		<%= f.text_field :author %>
	</p>
	<p>
		<%= f.label :Komentar %><br />
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

<%= link_to 'Depan', posts_path %>